"""Add image session and version models

Revision ID: bbbbaa244cd4
Revises: 005_workspace_collaboration
Create Date: 2025-08-25 16:47:39.204895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbbbaa244cd4'
down_revision: Union[str, None] = '005_workspace_collaboration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create image_generation_sessions table
    op.create_table('image_generation_sessions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('conversation_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('theme', sa.String(length=255), nullable=False),
    sa.Column('base_prompt', sa.Text(), nullable=False),
    sa.Column('evolution_history', sa.JSON(), nullable=True),
    sa.Column('selected_version_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True, default=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, default=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_generation_sessions_conversation_id'), 'image_generation_sessions', ['conversation_id'], unique=False)
    
    # Create image_generation_versions table
    op.create_table('image_generation_versions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('session_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=True, default=''),
    sa.Column('style', sa.String(length=50), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('generated_image_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True, default='generating'),
    sa.Column('is_selected', sa.Boolean(), nullable=True, default=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, default=False),
    sa.Column('generation_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['generated_image_id'], ['generated_images.id'], ),
    sa.ForeignKeyConstraint(['parent_version_id'], ['image_generation_versions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['image_generation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_generation_versions_session_id'), 'image_generation_versions', ['session_id'], unique=False)
    
    # Add foreign key for selected_version_id after table creation
    op.create_foreign_key('fk_image_generation_sessions_selected_version_id', 'image_generation_sessions', 'image_generation_versions', ['selected_version_id'], ['id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_image_generation_sessions_selected_version_id', 'image_generation_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_image_generation_versions_session_id'), table_name='image_generation_versions')
    op.drop_table('image_generation_versions')
    op.drop_index(op.f('ix_image_generation_sessions_conversation_id'), table_name='image_generation_sessions')
    op.drop_table('image_generation_sessions')
    # ### end Alembic commands ###